<a href="https://colab.research.google.com/github/hm-jeong/Deep-learning-study/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [4]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

print(x_train)
print(x_train.shape)

print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [6]:
W = torch.zeros(1, requires_grad=True)
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [13]:
optimizer = optim.SGD([W, b], lr=0.01)


In [16]:
nb_epochs = 2000
for epoch in range(nb_epochs):

  hypothesis = x_train * W + b
  cost = torch.mean((hypothesis - y_train) ** 2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  100/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  200/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  300/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  400/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  500/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  600/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  700/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  800/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch  900/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1000/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1100/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1200/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1300/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1400/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1500/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1600/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1700/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1800/2000 W: 1.000, b: 0.000 Cost: 0.000000
Epoch 1900/2000 W: 1.000, b: 0.000 Cost: 0.000000
